version: "3.7"

services:
  jupyter:
    image: jupyter/pyspark-notebook:python-3.11
    depends_on:
      lakekeeper:
        condition: service_healthy
      bootstrap:
        condition: service_completed_successfully
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./notebooks:/home/jovyan/examples/
    networks:
      iceberg_lakekeeper_net:
    ports:
      - "8888:8888"

  debezium-iceberg:
    image: ghcr.io/memiiso/debezium-server-iceberg:latest
    container_name: debezium-server-iceberg
    networks:
      - iceberg_lakekeeper_net
    depends_on:
      - lakekeeper
      - minio
      - postgresqlsourcedb
      - mc
      - bootstrap
    volumes:
      - ./config/application.properties:/debezium/config/application.properties
    command: >
      bash -c "
      /debezium/run.sh
      "
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1

  lakekeeper:
    image: quay.io/lakekeeper/catalog:latest
    container_name: lakekeeper
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@db:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=info
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "/home/nonroot/lakekeeper", "healthcheck" ]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - 8181:8181
    networks:
      - iceberg_lakekeeper_net

  postgresqlsourcedb:
    image: debezium/example-postgres:2.5
    container_name: postgresql-source-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS="-E UTF8"
      - LANG=en_US.utf8
    networks:
      - iceberg_lakekeeper_net
    ports:
      - "5432:5432"

  migrate:
    image: quay.io/lakekeeper/catalog:latest-main
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@db:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@db:5432/postgres
      - RUST_LOG=info
    restart: "no"
    command: [ "migrate" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iceberg_lakekeeper_net

  bootstrap:
    image: curlimages/curl
    depends_on:
      lakekeeper:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
    restart: "no"
    command:
      - sh
      - -c
      - |
        set -e
        curl -w "%{http_code}" -X POST -v http://lakekeeper:8181/management/v1/bootstrap -H "Content-Type: application/json" --data '{"accept-terms-of-use": true}' -o /dev/null
        curl -w "%{http_code}" -X POST -v http://lakekeeper:8181/management/v1/warehouse -H "Content-Type: application/json" --data '{"warehouse-name": "iceberg_warehouse", "project-id": "00000000-0000-0000-0000-000000000000", "storage-profile": {"type": "s3", "bucket": "warehouse", "key-prefix": "", "assume-role-arn": null, "endpoint": "http://minio:9000", "region": "us-east-1", "path-style-access": true, "allow-alternative-protocols": true, "flavor": "minio", "sts-enabled": true}, "storage-credential": {"type": "s3", "credential-type": "access-key", "aws-access-key-id": "admin", "aws-secret-access-key": "password"}}' -o /dev/null
    networks:
      - iceberg_lakekeeper_net

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_BUCKET=warehouse
    networks:
      - iceberg_lakekeeper_net
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]

  mc:
    image: minio/mc
    container_name: mc
    networks:
      - iceberg_lakekeeper_net
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=demo
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse;
      exit 0;
      "

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - iceberg_lakekeeper_net

  duckdbui:
    image: datacatering/duckdb:v1.4.1
    container_name: duckdbui
    #    entrypoint: ["./duckdb", "-ui", "&&", "sleep", "infinity"]
    entrypoint: >
      /bin/sh -c "
      ./duckdb -ui;
      sleep infinity;
      "
    networks:
      - iceberg_lakekeeper_net
    ports:
      - "4213:4213"
    depends_on:
      - lakekeeper

networks:
  iceberg_lakekeeper_net:
    name: iceberg_lakekeeper_net